<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Lang_lib {

    public function language_list()
    {
        $countryArray = (object)array(

            'af'=>array('name'=>'Afrikaans'),
            'sq'=>array('name'=>'Albanian'),
            'am'=>array('name'=>'Amharic'),
            'ar'=>array('name'=>'Arabic'),
            'hy'=>array('name'=>'Armenian'),
            'az'=>array('name'=>'Azerbaijani'),
            'eu'=>array('name'=>'Basque'),
            'be'=>array('name'=>'Belarusian'),
            'bn'=>array('name'=>'Bengali'),
            'bs'=>array('name'=>'Bosnian'),
            'bg'=>array('name'=>'Bulgarian'),
            'ca'=>array('name'=>'Catalan'),
            'ce'=>array('name'=>'Cebuano'),
            'ny'=>array('name'=>'Chichewa'),
            'zh'=>array('name'=>'Chinese (Simplified)'),
            'zh'=>array('name'=>'Chinese (Traditional)'),
            'co'=>array('name'=>'Corsican'),
            'hr'=>array('name'=>'Croatian'),
            'cs'=>array('name'=>'Czech'),
            'da'=>array('name'=>'Danish'),
            'nl'=>array('name'=>'Dutch'),
            'en'=>array('name'=>'English'),
            'eo'=>array('name'=>'Esperanto'),
            'et'=>array('name'=>'Estonian'),
            'tl'=>array('name'=>'Filipino'),
            'fi'=>array('name'=>'Finnish'),
            'fr'=>array('name'=>'French'),
            'fy'=>array('name'=>'Frisian'),
            'gl'=>array('name'=>'Galician'),
            'ka'=>array('name'=>'Georgian'),
            'de'=>array('name'=>'German'),
            'el'=>array('name'=>'Greek'),
            'gu'=>array('name'=>'Gujarati'),
            'ht'=>array('name'=>'Haitian Creole'),
            'ha'=>array('name'=>'Hausa'),
            'ha'=>array('name'=>'Hawaiian'),
            'iw'=>array('name'=>'Hebrew'),
            'hi'=>array('name'=>'Hindi'),
            'hm'=>array('name'=>'Hmong'),
            'hu'=>array('name'=>'Hungarian'),
            'is'=>array('name'=>'Icelandic'),
            'ig'=>array('name'=>'Igbo'),
            'id'=>array('name'=>'Indonesian'),
            'ga'=>array('name'=>'Irish'),
            'it'=>array('name'=>'Italian'),
            'ja'=>array('name'=>'Japanese'),
            'jw'=>array('name'=>'Javanese'),
            'kn'=>array('name'=>'Kannada'),
            'kk'=>array('name'=>'Kazakh'),
            'km'=>array('name'=>'Khmer'),
            'ko'=>array('name'=>'Korean'),
            'ku'=>array('name'=>'Kurdish(Kurmanji)'),
            'ky'=>array('name'=>'Kyrgyz'),
            'lo'=>array('name'=>'Lao'),
            'la'=>array('name'=>'Latin'),
            'lv'=>array('name'=>'Latvian'),
            'lt'=>array('name'=>'Lithuanian'),
            'lb'=>array('name'=>'Luxembourgish'),
            'mk'=>array('name'=>'Macedonian'),
            'mg'=>array('name'=>'Malagasy'),
            'ms'=>array('name'=>'Malay'),
            'ml'=>array('name'=>'Malayalam'),
            'mt'=>array('name'=>'Maltese'),
            'mi'=>array('name'=>'Maori'),
            'mr'=>array('name'=>'Marathi'),
            'mn'=>array('name'=>'Mongolian'),
            'my'=>array('name'=>'Myanmar(Burmese)'),
            'ne'=>array('name'=>'Nepali'),
            'no'=>array('name'=>'Norwegian'),
            'ps'=>array('name'=>'Pashto'),
            'fa'=>array('name'=>'Persian'),
            'pl'=>array('name'=>'Polish'),
            'pt'=>array('name'=>'Portuguese'),
            'pa'=>array('name'=>'Punjabi'),
            'ro'=>array('name'=>'Romanian'),
            'ru'=>array('name'=>'Russian'),
            'sm'=>array('name'=>'Samoan'),
            'gd'=>array('name'=>'Scots Gaelic'),
            'sr'=>array('name'=>'Serbian'),
            'st'=>array('name'=>'Sesotho'),
            'sn'=>array('name'=>'Shona'),
            'sd'=>array('name'=>'Sindhi'),
            'si'=>array('name'=>'Sinhala'),
            'sk'=>array('name'=>'Slovak'),
            'sl'=>array('name'=>'Slovenian'),
            'so'=>array('name'=>'Somali'),
            'es'=>array('name'=>'Spanish'),
            'su'=>array('name'=>'Sundanese'),
            'sw'=>array('name'=>'Swahili'),
            'sv'=>array('name'=>'Swedish'),
            'tg'=>array('name'=>'Tajik'),
            'ta'=>array('name'=>'Tamil'),
            'te'=>array('name'=>'Telugu'),
            'th'=>array('name'=>'Thai'),
            'tr'=>array('name'=>'Turkish'),
            'uk'=>array('name'=>'Ukrainian'),
            'ur'=>array('name'=>'Urdu'),
            'uz'=>array('name'=>'Uzbek'),
            'vi'=>array('name'=>'Vietnamese'),
            'cy'=>array('name'=>'Welsh'),
            'xh'=>array('name'=>'Xhosa'),
            'yi'=>array('name'=>'Yiddish'),
            'yo'=>array('name'=>'Yoruba'),
            'zu'=>array('name'=>'Zulu'),
        );

        return $countryArray;
    }
}